import {
  COUNTRY_OPTIONS,
  DEPARTMENT_OPTIONS,
  JOB_TITLE_OPTIONS,
} from '@blackhr/shared-types';

export { COUNTRY_OPTIONS, DEPARTMENT_OPTIONS, JOB_TITLE_OPTIONS };

export const FILTER_COUNTRY_OPTIONS = ['', ...COUNTRY_OPTIONS] as const;
export const FILTER_DEPARTMENT_OPTIONS = ['', ...DEPARTMENT_OPTIONS] as const;
export const FILTER_JOB_TITLE_OPTIONS = ['', ...JOB_TITLE_OPTIONS] as const;

export const FORM_COUNTRY_OPTIONS = COUNTRY_OPTIONS;
export const FORM_DEPARTMENT_OPTIONS = DEPARTMENT_OPTIONS;
export const FORM_JOB_TITLE_OPTIONS = JOB_TITLE_OPTIONS;
